
export const LOAD_PRODUCTS = 'LOAD_PRODUCTS'
export const SET_BOX_DATA = 'SET_BOX_DATA'
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY'
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY'
export const UPDATE_QTY = 'UPDATE_QTY'
export const ADD_CART = 'ADD_CART'
export const LOAD_CART = 'LOAD_CART'
export const baseURL = 'http://localhost:5000/'
export const UPDATE_CART_QTY =  'UPDATE_CART_QTY' 
export const INCREASE_CART_QTY =  'INCREASE_CART_QTY' 
export const DECREASE_CART_QTY =  'DECREASE_CART_QTY' 
export const REMOVE_CART_ITEM =  'REMOVE_CART_ITEM' 
export const REGISTER_USER =  'REGISTER_USER'